Add Spring Boot samples for Azure
apache/camel-spring-boot-examples pull request #87
Opened 2022-09-19 10:40 UTC by hui1110

Replace this PR:  https://github.com/apache/camel-spring-boot-examples/pull/41

Add the following samples:

- Event Hubs
- Service Bus
- Service Bus JMS

2022-09-19 10:58 UTC, oscerd requested changes
All good, but all the examples doesn't have a README explaining how to run the example and how to create the cloud resources to run.

2022-09-20 04:44 UTC, oscerd approved these changes

2022-09-20 07:18 UTC, saragluna commented on pom.xml
> +    <module>azure</module>
indentation

2022-09-20 10:09 UTC, oscerd approved these changes

2022-09-20 12:04 UTC, merged

2022-09-20 12:04 UTC, oscerd commented
Thanks for the PR.